apiVersion: v1
kind: ConfigMap
metadata:
  name: book-manage
  namespace: library
data:
  THEME_COLOR: "Blue"
  MAX_COUNT: "20"
  DB_HOST: "mysql"
  DB_NAME: "book_db"
  DB_PORT: "3306"
  init.sql: |
    CREATE DATABASE IF NOT EXISTS book_db;
    USE book_db;

    CREATE TABLE IF NOT EXISTS books (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        author VARCHAR(255) NOT NULL,
        description TEXT
    );
 