apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: library
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS book_db;
    USE book_db;
    CREATE TABLE IF NOT EXISTS books (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255),
      author VARCHAR(255),
      description TEXT
    );