apiVersion: apps/v1
kind: Deployment
metadata:
    name: banking-system
spec:
   replicas: 3
   selector:
      matchLabels:
          app: banking
   template:
      metadata:
        labels:
          app: banking
      spec:
       containers:
        - name: banking-systems
          image: heyrohhh/banking-system:v3
          ports:
           - containerPort: 3000
          imagePullPolicy: always
          livenessProbe:
             httpGet:
                path: /health
                port: 3000
             initialDelaySeconds: 30
             periodSeconds: 10
          readnessProbe:
                path: /health
                port: 3000
                initialDelaySeconds: 30
                periodSeconds: 10
          resources:
             requests:
               cpu: 200m
               memory: 256Mi
             limits:
               cpu: 350m
               memory: 512Mi
---
# ---- Service

apiVersion: v1
kind: Service
metadata:
  name: banking-service
spec:
  type: LoadBalancer
  selector:
    app: banking
  ports:
   - protocol: TCP
     port: 80
     targetPort: 3000


      
